--- 
clone: 
  depth: 1
kind: pipeline
name: ArcadiaBuild
steps: 
  - name: ISO Pipeline
    image: archlinux:base-devel
    commands:
      - curl -fsSL "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" | bsdtar -C / -xvf -
      - pacman --noconfirm -Syyu mtools dosfstools squashfs-tools e2fsprogs erofs-utils arch-install-scripts xorriso neofetch archiso devtools
      - neofetch
      - mkdir /tmp/archiso
      - mkdir output
      - mkarchiso -v -w /tmp/archiso -o output iso
  - name: Publish
    image: plugins/github-release
    settings:
      api_key:
         from_secret: github_token
      files: output/*
      title: 0.1.1
    when: 
      event: tag
    trigger: 
      branch:
        - master 
